site_name: CodinGirls
site_description: 程序媛乐松会
site_author: support@pythongirls.org
site_url: http://codingirls.org/
theme_dir: _theme/united
theme: united

repo_url: https://github.com/CodinGirls/codingirls.main

pages:
- ['index.md', 'Home']
- ['proposals.md', '申办']
- ['events/index.md', '通告', '各地活动']
- ['guide/index.md', '教程', '综述']
- ['guide/howto.md', '教程', '怎样组织']
- ['guide/install.md', '教程', '如何安装']
- ['guide/hallo.md', '教程', '你好世界']
- ['guide/html.md', '教程', '美化应用']
- ['guide/deploy.md', '教程', '发布部署']
- ['guide/share.md', '教程', '分享心得']
- ['decode/index.md', '解码', '程序媛由来']
- ['encode/index.md', '编译', '成为程序媛']
- ['encode/awesome.md', '编译', 'Awesome']
- ['press/index.md', '报道', '宗旨']
- ['sponsor.md', '支持者']
- ['volunteer.md', '志愿者']

#copyright: Copyright &copy; 2014, <a href="http://weibo.com/pyconcn">PyConChina</a>.